name: Bug Report | 错误报告
title: '[Bug]: '
description: Report a bug in the application | 这里有只虫子
labels: 'bug'
body:
  - type: input
    id: bug_version
    attributes:
      label: Software Version | 软件版本
      description: Please enter the software version number <br> 请填写软件版本号
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description | 问题描述
      description: Please describe the issue you encountered <br> 描述一下你遇到的问题
    validations:
      required: true
  - type: textarea
    id: bug_log
    attributes:
      label: Error Log | 问题日志
      description: Please provide error logs (Button on the right side of the software title bar) <br> 请提供问题日志（软件标题栏右侧第一个按钮）
    validations:
      required: true
  - type: textarea
    id: bug_screenshot
    attributes:
      label: Screenshots | 问题截图
      description: Please provide screenshots of the issue (optional) <br> 请提供问题截图（可选）
    validations:
      required: false
